### ISSUE TITLE
🛑 ST37 Engarde Escrime reallocation

### ISSUE THREAD

**Issue by st37infra** [st37infra/upptime#4]
In [`88ee76b`](https://github.com/st37infra/upptime/commit/88ee76b54af8e4b1919301d4a51cb96e68535ff7
), ST37 Engarde Escrime (https://www.engarde-escrime.com) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by edelmoral** [comment]
Downtime due to unscheduled maintenance
